version: '3.8'

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ./data/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REDIS_HOSTNAME=redis
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_DATABASE_NAME=immich
      - IMMICH_VERSION=release
    ports:
      - '2283:3001'
    depends_on:
      - redis
      - database
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: immich
    volumes:
      - ./data/immich/postgres:/var/lib/postgresql/data
    restart: unless-stopped
