version: '3.8'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8123:8123'
    restart: unless-stopped
