version: '3.8'

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    ports:
      - '8089:8080'
    volumes:
      - ./data/stirling-pdf/trainingData:/usr/share/tesseract-ocr/4.00/tessdata
      - ./data/stirling-pdf/extraConfigs:/configs
      - ./data/stirling-pdf/logs:/logs
    environment:
      - DOCKER_ENABLE_SECURITY=false
    restart: unless-stopped
